// lib/services/language_service.dart

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  static const String _prefKey = 'language_code';
  Locale _locale = const Locale('en');
  bool _isInitialized = false;

  Locale get locale => _locale;
  String get currentLanguage => _locale.languageCode;

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'login': 'Login',
      'welcome_back': 'Welcome Back',
      'username': 'Username (MID)',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'admin_dashboard': 'Admin Dashboard',
      'user_dashboard': 'User Dashboard',
      'families': 'Families',
      'members': 'Members',
      'groups': 'Groups',
      'events': 'Events',
      'analytics': 'Analytics',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'logout': 'Logout',
      'theme': 'Theme',
      'language': 'Language',
      'search': 'Search',
      'add': 'Add',
      'edit': 'Edit',
      'delete': 'Delete',
      'save': 'Save',
      'cancel': 'Cancel',
      'confirmation': 'Confirmation',
      'are_you_sure': 'Are you sure?',
      'profile': 'Profile',
      'member_id': 'Member ID',
      'family_id': 'Family ID',
      'digital_id': 'Digital ID Card',
      'share': 'Share',
      'biometric_login': 'Biometric Login',
      'birth_date': 'Birth Date',
      'blood_group': 'Blood Group',
      'education': 'Education',
      'native_home': 'Native Home',
      'phone': 'Phone',
      'address': 'Address',
      'quick_actions': 'Quick Actions',
      'personal_info': 'Personal Information',
      'contact_info': 'Contact Information',
      'recent_events': 'Recent Events',
      'upcoming_events': 'Upcoming Events',
      'no_events': 'No events found',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'manager': 'Manager',
      'all_members': 'All Members',
      'managers': 'Managers',
      'notification_center': 'Notification Center',
      'send_notification': 'Send Notification',
      'send_reminder': 'Send Reminder',
      'profile_details': 'Profile Details',
      'marriage_status': 'Marriage Status',
      'father_name': 'Father Name',
      'mother_name': 'Mother Name',
      'gotra': 'Gotra',
      'demote_to_member': 'Demote to Member',
      'promote_to_manager': 'Promote to Manager',
      'demote_member': 'Demote Member',
      'promote_member': 'Promote Member',
      'are_you_sure_role': 'Are you sure you want to',
      'demote': 'Demote',
      'promote': 'Promote',
      'demoted_success': 'Member successfully demoted',
      'promoted_success': 'Member successfully promoted',
      'demote_subtitle': 'Remove manager privileges',
      'promote_subtitle': 'Grant manager privileges',
      'member_not_found': 'Member not found',
      'member_details': 'Member Details',
      'years': 'years',
      'social_media': 'Social Media',
      'admin_actions': 'Admin Actions',
      'share_profile': 'Share Profile',
      // Member Form Fields
      'full_name': 'Full Name',
      'surname': 'Surname',
      'required': 'Required',
      'add_member': 'Add Member',
      'edit_member': 'Edit Member',
      'update_member': 'Update Member',
      'tap_to_add_photo': 'Tap to add profile photo',
      'personal_information': 'Personal Information',
      'contact_information': 'Contact Information',
      'firms_business': 'Firms / Business Details',
      'family_information': 'Family Information',
      'tags': 'Tags',
      'add_tag': 'Add Tag (max 15 chars)',
      'add_firm': 'Add Firm',
      'firm_name': 'Firm Name',
      'dkt_family_id': 'DKT Family ID',
      'parent_member_id': 'Parent Member ID',
      'member_login_password': 'Member Login Password',
      'must_be_8_chars': 'Must be exactly 8 alphanumeric characters',
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'facebook': 'Facebook',
      'google_map_link': 'Google Map Link',
      'select': 'Select',
      'unmarried': 'Unmarried',
      'married': 'Married',
      // QR Scanner
      'scan_qr': 'Scan QR Code',
      'scan_member_qr': 'Scan Member QR',
      'point_camera': 'Point camera at QR code',
      'scanning': 'Scanning...',
      'scan_to_save_contact': 'Scan to Save Contact',
      'member_profile': 'Member Profile',
      // Search
      'search_members_hint': 'Search by name or MID',
      'search_managers_hint': 'Search managers',
      'no_members_found': 'No members found',
      'no_members_match': 'No members match your search',
      // Digital ID
      'community_pride': 'Community Pride • Digital Identity',
      'age': 'Age',
      'firms': 'Firms',
    },
    'gu': {
      'login': 'લોગિન',
      'welcome_back': 'સ્વાગત છે',
      'username': 'યુઝરનેમ (MID)',
      'password': 'પાસવર્ડ',
      'forgot_password': 'પાસવર્ડ ભૂલી ગયા છો?',
      'admin_dashboard': 'એડમિન ડેશબોર્ડ',
      'user_dashboard': 'યુઝર ડેશબોર્ડ',
      'families': 'પરિવારો',
      'members': 'સભ્યો',
      'groups': 'ગ્રૂપ',
      'events': 'કાર્યક્રમો',
      'analytics': 'એનાલિટિક્સ',
      'notifications': 'નોટિફિકેશન',
      'settings': 'સેટિંગ્સ',
      'logout': 'લોગઆઉટ',
      'theme': 'થીમ',
      'language': 'ભાષા',
      'search': 'શોધો',
      'add': 'ઉમેરો',
      'edit': 'ફેરફાર કરો',
      'delete': 'ડીલીટ',
      'save': 'સાચવો',
      'cancel': 'રદ કરો',
      'confirmation': 'ખાતરી',
      'are_you_sure': 'શું તમે ખાતરીપૂર્વક કરવા માંગો છો?',
      'profile': 'પ્રોફાઇલ',
      'member_id': 'સભ્ય ID',
      'family_id': 'પરિવાર ID',
      'digital_id': 'ડિજિટલ ID કાર્ડ',
      'share': 'શેર કરો',
      'biometric_login': 'બાયોમેટ્રિક લોગિન',
      'birth_date': 'જન્મ તારીખ',
      'blood_group': 'બ્લડ ગ્રુપ',
      'education': 'શિક્ષણ',
      'native_home': 'વતન',
      'phone': 'ફોન',
      'address': 'સરનામું',
      'quick_actions': 'ઝડપી કાર્યો',
      'personal_info': 'વ્યક્તિગત માહિતી',
      'contact_info': 'સંપર્ક માહિતી',
      'recent_events': 'તાજેતરના કાર્યક્રમો',
      'upcoming_events': 'આવનારા કાર્યક્રમો',
      'no_events': 'કોઈ કાર્યક્રમ મળ્યો નથી',
      'loading': 'લોડ થઈ રહ્યું છે...',
      'error': 'ભૂલ',
      'success': 'સફળતા',
      'manager': 'મેનેજર',
      'all_members': 'તમામ સભ્યો',
      'managers': 'મેનેજરો',
      'notification_center': 'નોટિફિકેશન સેન્ટર',
      'send_notification': 'નોટિફિકેશન મોકલો',
      'send_reminder': 'રિમાઇન્ડર મોકલો',
      'profile_details': 'પ્રોફાઇલ વિગતો',
      'marriage_status': 'વૈવાહિક સ્થિતિ',
      'father_name': 'પિતાનું નામ',
      'mother_name': 'માતાનું નામ',
      'gotra': 'ગોત્ર',
      'demote_to_member': 'સભ્ય તરીકે નિમણૂક',
      'promote_to_manager': 'મેનેજર તરીકે નિમણૂક',
      'demote_member': 'સભ્ય બનાવો',
      'promote_member': 'મેનેજર બનાવો',
      'are_you_sure_role': 'શું તમે ખાતરીપૂર્વક કરવા માંગો છો',
      'demote': 'સભ્ય બનાવો',
      'promote': 'મેનેજર બનાવો',
      'demoted_success': 'સભ્યને સફળતાપૂર્વક સભ્ય બનાવવામાં આવ્યા',
      'promoted_success': 'સભ્યને સફળતાપૂર્વક મેનેજર બનાવવામાં આવ્યા',
      'demote_subtitle': 'મેનેજર હકો દૂર કરો',
      'promote_subtitle': 'મેનેજર હકો આપો',
      'member_not_found': 'સભ્ય મળ્યા નથી',
      'member_details': 'સભ્યની વિગતો',
      'years': 'વર્ષ',
      'social_media': 'સોશિયલ મીડિયા',
      'admin_actions': 'એડમિન કાર્યો',
      'share_profile': 'પ્રોફાઇલ શેર કરો',
      // Member Form Fields
      'full_name': 'પૂરું નામ',
      'surname': 'અટક',
      'required': 'જરૂરી',
      'add_member': 'સભ્ય ઉમેરો',
      'edit_member': 'સભ્યમાં ફેરફાર કરો',
      'update_member': 'સભ્ય અપડેટ કરો',
      'tap_to_add_photo': 'ફોટો ઉમેરવા માટે ટેપ કરો',
      'personal_information': 'વ્યક્તિગત માહિતી',
      'contact_information': 'સંપર્ક માહિતી',
      'firms_business': 'ફર્મ / વ્યવસાય વિગતો',
      'family_information': 'પરિવાર માહિતી',
      'tags': 'ટેગ્સ',
      'add_tag': 'ટેગ ઉમેરો (મહત્તમ 15 અક્ષરો)',
      'add_firm': 'ફર્મ ઉમેરો',
      'firm_name': 'ફર્મનું નામ',
      'dkt_family_id': 'DKT પરિવાર ID',
      'parent_member_id': 'પેરેન્ટ સભ્ય ID',
      'member_login_password': 'સભ્ય લોગિન પાસવર્ડ',
      'must_be_8_chars': '8 આલ્ફાન્યુમેરિક અક્ષરો હોવા જોઈએ',
      'whatsapp': 'વોટ્સએપ',
      'instagram': 'ઇન્સ્ટાગ્રામ',
      'facebook': 'ફેસબુક',
      'google_map_link': 'ગૂગલ મેપ લિંક',
      'select': 'પસંદ કરો',
      'unmarried': 'અપરણીત',
      'married': 'પરણીત',
      // QR Scanner
      'scan_qr': 'QR કોડ સ્કેન કરો',
      'scan_member_qr': 'સભ્ય QR સ્કેન કરો',
      'point_camera': 'QR કોડ પર કેમેરા પોઇન્ટ કરો',
      'scanning': 'સ્કેન કરી રહ્યા છીએ...',
      'scan_to_save_contact': 'સંપર્ક સાચવવા માટે સ્કેન કરો',
      'member_profile': 'સભ્ય પ્રોફાઇલ',
      // Search
      'search_members_hint': 'નામ અથવા MID દ્વારા શોધો',
      'search_managers_hint': 'મેનેજરો શોધો',
      'no_members_found': 'કોઈ સભ્યો મળ્યા નથી',
      'no_members_match': 'તમારી શોધ સાથે કોઈ સભ્યો મેળ ખાતા નથી',
      // Digital ID
      'community_pride': 'સમુદાય ગૌરવ • ડિજિટલ ઓળખ',
      'age': 'ઉંમર',
      'firms': 'ફર્મ્સ',
    },
  };

  String translate(String key) {
    return _translations[_locale.languageCode]?[key] ??
        _translations['en']?[key] ??
        key;
  }

  Future<void> initialize() async {
    if (_isInitialized) return;

    final prefs = await SharedPreferences.getInstance();
    final savedLocale = prefs.getString(_prefKey);
    if (savedLocale != null) {
      _locale = Locale(savedLocale);
    }
    _isInitialized = true;
    notifyListeners();
  }

  Future<void> setLocale(String languageCode) async {
    _locale = Locale(languageCode);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefKey, languageCode);
    notifyListeners();
  }

  Future<void> setLanguage(String languageCode) => setLocale(languageCode);

  String t(String key) => translate(key);
}
