// lib/services/language_service.dart

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  static const String _prefKey = 'language_code';
  Locale _locale = const Locale('en');
  bool _isInitialized = false;

  Locale get locale => _locale;
  String get currentLanguage => _locale.languageCode;

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'login': 'Login',
      'welcome_back': 'Welcome Back',
      'welcome': 'Welcome',
      'username': 'Username (MID)',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'admin_dashboard': 'Admin Dashboard',
      'user_dashboard': 'User Dashboard',
      'families': 'Families',
      'members': 'Members',
      'groups': 'Groups',
      'events': 'Events',
      'analytics': 'Analytics',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'logout': 'Logout',
      'theme': 'Theme',
      'language': 'Language',
      'preferences': 'Preferences',
      'search': 'Search',
      'add': 'Add',
      'edit': 'Edit',
      'delete': 'Delete',
      'save': 'Save',
      'cancel': 'Cancel',
      'confirmation': 'Confirmation',
      'are_you_sure': 'Are you sure?',
      'profile': 'Profile',
      'member_id': 'Member ID',
      'family_id': 'Family ID',
      'digital_id': 'Digital ID Card',
      'share': 'Share',
      'biometric_login': 'Biometric Login',
      'birth_date': 'Birth Date',
      'blood_group': 'Blood Group',
      'education': 'Education',
      'native_home': 'Native Home',
      'phone': 'Phone',
      'address': 'Address',
      'quick_actions': 'Quick Actions',
      'personal_info': 'Personal Information',
      'contact_info': 'Contact Information',
      'recent_events': 'Recent Events',
      'upcoming_events': 'Upcoming Events',
      'no_events': 'No events found',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'manager': 'Manager',
      'all_members': 'All Members',
      'managers': 'Managers',
      'notification_center': 'Notification Center',
      'send_notification': 'Send Notification',
      'send_reminder': 'Send Reminder',
      'profile_details': 'Profile Details',
      'marriage_status': 'Marriage Status',
      'father_name': 'Father Name',
      'mother_name': 'Mother Name',
      'gotra': 'Gotra',
      'demote_to_member': 'Demote to Member',
      'promote_to_manager': 'Promote to Manager',
      'demote_member': 'Demote Member',
      'promote_member': 'Promote Member',
      'are_you_sure_role': 'Are you sure you want to',
      'demote': 'Demote',
      'promote': 'Promote',
      'demoted_success': 'Member successfully demoted',
      'promoted_success': 'Member successfully promoted',
      'demote_subtitle': 'Remove manager privileges',
      'promote_subtitle': 'Grant manager privileges',
      'member_not_found': 'Member not found',
      'member_details': 'Member Details',
      'years': 'years',
      'social_media': 'Social Media',
      'admin_actions': 'Admin Actions',
      'share_profile': 'Share Profile',
      // Member Form Fields
      'full_name': 'Full Name',
      'surname': 'Surname',
      'required': 'Required',
      'add_member': 'Add Member',
      'edit_member': 'Edit Member',
      'update_member': 'Update Member',
      'tap_to_add_photo': 'Tap to add profile photo',
      'personal_information': 'Personal Information',
      'contact_information': 'Contact Information',
      'firms_business': 'Firms / Business Details',
      'family_information': 'Family Information',
      'tags': 'Tags',
      'add_tag': 'Add Tag (max 15 chars)',
      'add_firm': 'Add Firm',
      'firm_name': 'Firm Name',
      'dkt_family_id': 'DKT Family ID',
      'parent_member_id': 'Parent Member ID',
      'member_login_password': 'Member Login Password',
      'must_be_8_chars': 'Must be exactly 8 alphanumeric characters',
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'facebook': 'Facebook',
      'google_map_link': 'Google Map Link',
      'select': 'Select',
      'unmarried': 'Unmarried',
      'married': 'Married',
      // QR Scanner
      'scan_qr': 'Scan QR Code',
      'scan_member_qr': 'Scan Member QR',
      'point_camera': 'Point camera at QR code',
      'scanning': 'Scanning...',
      'scan_to_save_contact': 'Scan to Save Contact',
      'member_profile': 'Member Profile',
      // Search
      'search_members_hint': 'Search by name or MID',
      'search_managers_hint': 'Search managers',
      'no_members_found': 'No members found',
      'no_members_match': 'No members match your search',
      // Digital ID
      'community_pride': 'Community Pride • Digital Identity',
      'age': 'Age',
      'firms': 'Firms',
      // Settings screen specific
      'receive_notifications': 'Receive notifications',
      'use_dark_theme': 'Use dark theme',
      'family': 'Family',
      'view_family_members': 'View family members',
      'support': 'Support',
      'help_faq': 'Help & FAQ',
      'about': 'About',
      'confirm_logout': 'Are you sure you want to logout?',
      'organization': 'Organization',
      'manage_families': 'Manage families',
      'manage_members': 'Manage members',
      'manage_groups_subtitle': 'Create and manage groups',
      'manage_events_subtitle': 'Create and manage events',
      'send_custom_messages': 'Send custom messages and alerts',
      'view_stats': 'View analytics and stats',
      'family_members': 'Family & Members',
      'insights': 'Insights',
      'advanced': 'Advanced',
      'admin_settings': 'Admin Settings',
      'text_size': 'Text size',
      'text_size_small': 'Small',
      'text_size_normal': 'Normal',
      'text_size_large': 'Large',
      'reset_settings': 'Reset app settings',
      'reset_settings_desc': 'Restore theme, language and text size to default',
      'reset_done': 'Settings reset successfully',
      // Calendar
      'calendar': 'Calendar',
      'select_date': 'Select a date',
      'events_for': 'Events for',
      'no_events_today': 'No events on this day',
      'today': 'Today',
      'month': 'Month',
      'year': 'Year',
      'filter_events': 'Filter Events',
      'all_events': 'All Events',
      'upcoming_only': 'Upcoming Only',
      'past_events': 'Past Events',
      'event_type': 'Event Type',
      'general': 'General',
      'meeting': 'Meeting',
      'celebration': 'Celebration',
      'reminder': 'Reminder',
      'view_mode': 'View Mode',
      'month_view': 'Month View',
      'week_view': 'Week View',
      'event_details': 'Event Details',
      'location': 'Location',
      'time': 'Time',
      'description': 'Description',
      'export_calendar': 'Export Calendar',
      'show_past_events': 'Show Past Events',
      'event_reminders': 'Event Reminders',
      'enable_reminders': 'Enable Reminders',
      'close': 'Close',
      // Enhanced Dashboard
      'global_search': 'Global Search',
      'search_members': 'Search Members',
      'filter_by': 'Filter By',
      'city': 'City',
      'marital_status': 'Marital Status',
      'all': 'All',
      'random_suggestions': 'Random Suggestions',
      'suggested_members': 'Suggested Members',
      'new_members': 'New Members',
      'recent_activity': 'Recent Activity',
      'community_activity': 'Community Activity',
      'view_family_tree': 'View Family Tree',
      'family_tree': 'Family Tree',
      'no_results': 'No results found',
      'clear_filters': 'Clear Filters',
      'apply_filters': 'Apply Filters',
      'member_suggestions': 'Member Suggestions',
      'discover_members': 'Discover Members',
      'view_all': 'View All',
      'statistics': 'Statistics',
      'total_members': 'Total Members',
      'active_members': 'Active Members',
      'new_this_month': 'New This Month',
      'age_distribution': 'Age Distribution',
      'location_wise': 'Location Wise',
      'education_stats': 'Education Stats',
      'recommended_for_you': 'Recommended For You',
      'similar_interests': 'Similar Interests',
      'same_city': 'Same City',
      'same_blood_group': 'Same Blood Group',
      'connect': 'Connect',
      'view_profile': 'View Profile',
      'quick_stats': 'Quick Stats',
      'trending': 'Trending',
      'most_viewed': 'Most Viewed',
      'recently_joined': 'Recently Joined',
      'refresh': 'Refresh',
      'view_members': 'View Members',
      'manage_managers': 'Manage Managers',
      'manage_managers_subtitle': 'View and manage system managers',
      'my_family_tree': 'My Family Tree',
      'my_family_members': 'My Family Members',
      'none': 'None',
      'head': 'Head',
      'relation_to_head': 'Relation to Head',
      'head_of_family': 'Head of Family',
      'wife': 'Wife',
      'daughter': 'Daughter',
      'son': 'Son',
      'daughter_in_law': 'Daughter in Law',
      'grandson': 'Grandson',
      'grandsister': 'Grandsister',
      'relation_to_main_head': 'Head of Sub-family Relation to Main Head',
      'joint_family_linking': 'Joint Family Linking',
      'whole_family': 'Whole Family',
      'my_family': 'My Family',
      'male': 'Male',
      'female': 'Female',
      'view_ancestry': 'View Ancestry',
      'member_spotlight': 'Member Spotlight',
    },
    'gu': {
      'login': 'લોગિન',
      'welcome_back': 'સ્વાગત છે',
      'welcome': 'સ્વાગત છે',
      'username': 'યુઝરનેમ (MID)',
      'password': 'પાસવર્ડ',
      'forgot_password': 'પાસવર્ડ ભૂલી ગયા છો?',
      'admin_dashboard': 'એડમિન ડેશબોર્ડ',
      'user_dashboard': 'યુઝર ડેશબોર્ડ',
      'families': 'પરિવારો',
      'members': 'સભ્યો',
      'groups': 'ગ્રૂપ',
      'events': 'કાર્યક્રમો',
      'analytics': 'એનાલિટિક્સ',
      'notifications': 'નોટિફિકેશન',
      'settings': 'સેટિંગ્સ',
      'logout': 'લોગઆઉટ',
      'theme': 'થીમ',
      'language': 'ભાષા',
      'preferences': 'પસંદગીઓ',
      'search': 'શોધો',
      'add': 'ઉમેરો',
      'edit': 'ફેરફાર કરો',
      'delete': 'ડીલીટ',
      'save': 'સાચવો',
      'cancel': 'રદ કરો',
      'confirmation': 'ખાતરી',
      'are_you_sure': 'શું તમે ખાતરીપૂર્વક કરવા માંગો છો?',
      'profile': 'પ્રોફાઇલ',
      'member_id': 'સભ્ય ID',
      'family_id': 'પરિવાર ID',
      'digital_id': 'ડિજિટલ ID કાર્ડ',
      'share': 'શેર કરો',
      'biometric_login': 'બાયોમેટ્રિક લોગિન',
      'birth_date': 'જન્મ તારીખ',
      'blood_group': 'બ્લડ ગ્રુપ',
      'education': 'શિક્ષણ',
      'native_home': 'વતન',
      'phone': 'ફોન',
      'address': 'સરનામું',
      'quick_actions': 'ઝડપી કાર્યો',
      'personal_info': 'વ્યક્તિગત માહિતી',
      'contact_info': 'સંપર્ક માહિતી',
      'recent_events': 'તાજેતરના કાર્યક્રમો',
      'upcoming_events': 'આવનારા કાર્યક્રમો',
      'no_events': 'કોઈ કાર્યક્રમ મળ્યો નથી',
      'loading': 'લોડ થઈ રહ્યું છે...',
      'error': 'ભૂલ',
      'success': 'સફળતા',
      'manager': 'મેનેજર',
      'all_members': 'તમામ સભ્યો',
      'managers': 'મેનેજરો',
      'notification_center': 'નોટિફિકેશન સેન્ટર',
      'send_notification': 'નોટિફિકેશન મોકલો',
      'send_reminder': 'રિમાઇન્ડર મોકલો',
      'profile_details': 'પ્રોફાઇલ વિગતો',
      'marriage_status': 'વૈવાહિક સ્થિતિ',
      'father_name': 'પિતાનું નામ',
      'mother_name': 'માતાનું નામ',
      'gotra': 'ગોત્ર',
      'demote_to_member': 'સભ્ય તરીકે નિમણૂક',
      'promote_to_manager': 'મેનેજર તરીકે નિમણૂક',
      'demote_member': 'સભ્ય બનાવો',
      'promote_member': 'મેનેજર બનાવો',
      'are_you_sure_role': 'શું તમે ખાતરીપૂર્વક કરવા માંગો છો',
      'demote': 'સભ્ય બનાવો',
      'promote': 'મેનેજર બનાવો',
      'demoted_success': 'સભ્યને સફળતાપૂર્વક સભ્ય બનાવવામાં આવ્યા',
      'promoted_success': 'સભ્યને સફળતાપૂર્વક મેનેજર બનાવવામાં આવ્યા',
      'demote_subtitle': 'મેનેજર હકો દૂર કરો',
      'promote_subtitle': 'મેનેજર હકો આપો',
      'member_not_found': 'સભ્ય મળ્યા નથી',
      'member_details': 'સભ્યની વિગતો',
      'years': 'વર્ષ',
      'social_media': 'સોશિયલ મીડિયા',
      'admin_actions': 'એડમિન કાર્યો',
      'share_profile': 'પ્રોફાઇલ શેર કરો',
      // Member Form Fields
      'full_name': 'પૂરું નામ',
      'surname': 'અટક',
      'required': 'જરૂરી',
      'add_member': 'સભ્ય ઉમેરો',
      'edit_member': 'સભ્યમાં ફેરફાર કરો',
      'update_member': 'સભ્ય અપડેટ કરો',
      'tap_to_add_photo': 'ફોટો ઉમેરવા માટે ટેપ કરો',
      'personal_information': 'વ્યક્તિગત માહિતી',
      'contact_information': 'સંપર્ક માહિતી',
      'firms_business': 'ફર્મ / વ્યવસાય વિગતો',
      'family_information': 'પરિવાર માહિતી',
      'tags': 'ટેગ્સ',
      'add_tag': 'ટેગ ઉમેરો (મહત્તમ 15 અક્ષરો)',
      'add_firm': 'ફર્મ ઉમેરો',
      'firm_name': 'ફર્મનું નામ',
      'dkt_family_id': 'DKT પરિવાર ID',
      'parent_member_id': 'પેરેન્ટ સભ્ય ID',
      'member_login_password': 'સભ્ય લોગિન પાસવર્ડ',
      'must_be_8_chars': '8 આલ્ફાન્યુમેરિક અક્ષરો હોવા જોઈએ',
      'whatsapp': 'વોટ્સએપ',
      'instagram': 'ઇન્સ્ટાગ્રામ',
      'facebook': 'ફેસબુક',
      'google_map_link': 'ગૂગલ મેપ લિંક',
      'select': 'પસંદ કરો',
      'unmarried': 'અપરણીત',
      'married': 'પરણીત',
      // QR Scanner
      'scan_qr': 'QR કોડ સ્કેન કરો',
      'scan_member_qr': 'સભ્ય QR સ્કેન કરો',
      'point_camera': 'QR કોડ પર કેમેરા પોઇન્ટ કરો',
      'scanning': 'સ્કેન કરી રહ્યા છીએ...',
      'scan_to_save_contact': 'સંપર્ક સાચવવા માટે સ્કેન કરો',
      'member_profile': 'સભ્ય પ્રોફાઇલ',
      // Search
      'search_members_hint': 'નામ અથવા MID દ્વારા શોધો',
      'search_managers_hint': 'મેનેજરો શોધો',
      'no_members_found': 'કોઈ સભ્યો મળ્યા નથી',
      'no_members_match': 'તમારી શોધ સાથે કોઈ સભ્યો મેળ ખાતા નથી',
      // Digital ID
      'community_pride': 'સમુદાય ગૌરવ • ડિજિટલ ઓળખ',
      'age': 'ઉંમર',
      'firms': 'ફર્મ્સ',
      // Settings screen specific
      'receive_notifications': 'નોટિફિકેશન મેળવો',
      'use_dark_theme': 'ડાર્ક થીમ ઉપયોગ કરો',
      'family': 'પરિવાર',
      'view_family_members': 'પરિવારના સભ્યો જુઓ',
      'support': 'સપોર્ટ',
      'help_faq': 'મદદ અને પ્રશ્નોત્તરી',
      'about': 'વિશે',
      'confirm_logout': 'શું તમે ખરેખર લોગઆઉટ કરવા માંગો છો?',
      'organization': 'સંગઠન',
      'manage_families': 'પરિવારો મેનેજ કરો',
      'manage_members': 'સભ્યો મેનેજ કરો',
      'manage_groups_subtitle': 'ગ્રૂપ બનાવો અને મેનેજ કરો',
      'manage_events_subtitle': 'કાર્યક્રમો બનાવો અને મેનેજ કરો',
      'send_custom_messages': 'કસ્ટમ મેસેજ અને એલર્ટ મોકલો',
      'view_stats': 'આંકડા અને વિશ્લેષણ જુઓ',
      'family_members': 'પરિવાર અને સભ્યો',
      'insights': 'ઇન્સાઇટ્સ',
      'advanced': 'એડવાન્સ',
      'admin_settings': 'એડમિન સેટિંગ્સ',
      'text_size': 'ટેક્સ્ટ સાઈઝ',
      'text_size_small': 'નાનું',
      'text_size_normal': 'સામાન્ય',
      'text_size_large': 'મોટું',
      'reset_settings': 'એપ સેટિંગ્સ રીસેટ કરો',
      'reset_settings_desc': 'થીમ, ભાષા અને ટેક્સ્ટ સાઈઝ ડિફોલ્ટ પર લાવો',
      'reset_done': 'સેટિંગ્સ સફળતાપૂર્વક રીસેટ થયા',
      // Calendar
      'calendar': 'કેલેન્ડર',
      'select_date': 'તારીખ પસંદ કરો',
      'events_for': 'માટે કાર્યક્રમો',
      'no_events_today': 'આ દિવસે કોઈ કાર્યક્રમ નથી',
      'today': 'આજે',
      'month': 'મહિનો',
      'year': 'વર્ષ',
      'filter_events': 'કાર્યક્રમો ફિલ્ટર કરો',
      'all_events': 'તમામ કાર્યક્રમો',
      'upcoming_only': 'ફક્ત આવનારા',
      'past_events': 'ભૂતકાળના કાર્યક્રમો',
      'event_type': 'કાર્યક્રમનો પ્રકાર',
      'general': 'સામાન્ય',
      'meeting': 'મીટિંગ',
      'celebration': 'ઉજવણી',
      'reminder': 'રિમાઇન્ડર',
      'view_mode': 'દૃશ્ય મોડ',
      'month_view': 'મહિનાનું દૃશ્ય',
      'week_view': 'અઠવાડિયાનું દૃશ્ય',
      'event_details': 'કાર્યક્રમની વિગતો',
      'location': 'સ્થાન',
      'time': 'સમય',
      'description': 'વર્ણન',
      'export_calendar': 'કેલેન્ડર એક્સપોર્ટ કરો',
      'show_past_events': 'ભૂતકાળના કાર્યક્રમો બતાવો',
      'event_reminders': 'કાર્યક્રમ રિમાઇન્ડર્સ',
      'enable_reminders': 'રિમાઇન્ડર્સ સક્ષમ કરો',
      'close': 'બંધ કરો',
      // Enhanced Dashboard
      'global_search': 'ગ્લોબલ શોધ',
      'search_members': 'સભ્યો શોધો',
      'filter_by': 'ફિલ્ટર કરો',
      'city': 'શહેર',
      'marital_status': 'વૈવાહિક સ્થિતિ',
      'all': 'બધા',
      'random_suggestions': 'રેન્ડમ સૂચનો',
      'suggested_members': 'સૂચિત સભ્યો',
      'new_members': 'નવા સભ્યો',
      'recent_activity': 'તાજેતરની પ્રવૃત્તિ',
      'community_activity': 'સમુદાય પ્રવૃત્તિ',
      'view_family_tree': 'પરિવાર વૃક્ષ જુઓ',
      'family_tree': 'પરિવાર વૃક્ષ',
      'no_results': 'કોઈ પરિણામ મળ્યું નથી',
      'clear_filters': 'ફિલ્ટર સાફ કરો',
      'apply_filters': 'ફિલ્ટર લાગુ કરો',
      'member_suggestions': 'સભ્ય સૂચનો',
      'discover_members': 'સભ્યો શોધો',
      'view_all': 'બધું જુઓ',
      'statistics': 'આંકડા',
      'total_members': 'કુલ સભ્યો',
      'active_members': 'સક્રિય સભ્યો',
      'new_this_month': 'આ મહિનામાં નવા',
      'age_distribution': 'ઉંમર વિતરણ',
      'location_wise': 'સ્થાન મુજબ',
      'education_stats': 'શિક્ષણ આંકડા',
      'recommended_for_you': 'તમારા માટે ભલામણ',
      'similar_interests': 'સમાન રુચિઓ',
      'same_city': 'સમાન શહેર',
      'same_blood_group': 'સમાન બ્લડ ગ્રુપ',
      'connect': 'કનેક્ટ કરો',
      'view_profile': 'પ્રોફાઇલ જુઓ',
      'quick_stats': 'ઝડપી આંકડા',
      'trending': 'ટ્રેન્ડિંગ',
      'most_viewed': 'સૌથી વધુ જોવાયેલ',
      'recently_joined': 'તાજેતરમાં જોડાયા',
      'refresh': 'રિફ્રેશ',
      'view_members': 'સભ્યો જુઓ',
      'manage_managers': 'મેનેજરો મેનેજ કરો',
      'manage_managers_subtitle': 'સિસ્ટમ મેનેજરો જુઓ અને મેનેજ કરો',
      'my_family_tree': 'મારું પરિવાર વૃક્ષ',
      'my_family_members': 'મારા પરિવારના સભ્યો',
      'none': 'કોઈ નહીં',
      'head': 'મોભી',
      'relation_to_head': 'મોભી સાથેનો સંબંધ',
      'head_of_family': 'પરિવારના મોભી',
      'wife': 'પત્ની',
      'daughter': 'પુત્રી',
      'son': 'પુત્ર',
      'daughter_in_law': 'પુત્રવધૂ',
      'grandson': 'પૌત્ર',
      'grandsister': 'ગ્રાન્ડસિસ્ટર',
      'relation_to_main_head': 'પેટા-પરિવારના મોભીનો મુખ્ય મોભી સાથેનો સંબંધ',
      'joint_family_linking': 'સંયુક્ત પરિવાર જોડાણ',
      'whole_family': 'આખો પરિવાર',
      'my_family': 'મારો પરિવાર',
      'male': 'પુરુષ',
      'female': 'સ્ત્રી',
      'view_ancestry': 'વંશાવલી જુઓ',
      'member_spotlight': 'સભ્ય સ્પોટલાઇટ',
    },
  };

  String translate(String key) {
    return _translations[_locale.languageCode]?[key] ??
        _translations['en']?[key] ??
        key;
  }

  Future<void> initialize() async {
    if (_isInitialized) return;

    final prefs = await SharedPreferences.getInstance();
    final savedLocale = prefs.getString(_prefKey);
    if (savedLocale != null) {
      _locale = Locale(savedLocale);
    }
    _isInitialized = true;
    notifyListeners();
  }

  Future<void> setLocale(String languageCode) async {
    _locale = Locale(languageCode);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefKey, languageCode);
    notifyListeners();
  }

  Future<void> setLanguage(String languageCode) => setLocale(languageCode);

  String t(String key) => translate(key);
}
