// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd-lC5yCIlrP4pqaAr3U2Hd1rcCvK25Zw',
    appId: '1:30491497060:web:29e53febbdc056c3104571',
    messagingSenderId: '30491497060',
    projectId: 'com-app-project',
    authDomain: 'com-app-project.firebaseapp.com',
    storageBucket: 'com-app-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKKJyuA-O4suhPGOQJT_rt0Wkrly416wk',
    appId: '1:735355664522:android:1f659a826cade6b76b9573',
    messagingSenderId: '30491497060',
    projectId: 'com-app-project',
    storageBucket: 'com-app-project.firebasestorage.app',
    databaseURL: 'https://com-app-project.asia-south1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6BUcWNT5bna4tgeSMPWs2fts0CZOLYng',
    appId: '1:30491497060:ios:33fbdfec0f7c2633104571',
    messagingSenderId: '30491497060',
    projectId: 'com-app-project',
    storageBucket: 'com-app-project.firebasestorage.app',
    iosBundleId: 'com.example.commApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6BUcWNT5bna4tgeSMPWs2fts0CZOLYng',
    appId: '1:30491497060:ios:33fbdfec0f7c2633104571',
    messagingSenderId: '30491497060',
    projectId: 'com-app-project',
    storageBucket: 'com-app-project.firebasestorage.app',
    iosBundleId: 'com.example.commApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd-lC5yCIlrP4pqaAr3U2Hd1rcCvK25Zw',
    appId: '1:30491497060:web:406518662020d1de104571',
    messagingSenderId: '30491497060',
    projectId: 'com-app-project',
    authDomain: 'com-app-project.firebaseapp.com',
    storageBucket: 'com-app-project.firebasestorage.app',
  );
}
